### ISSUE TITLE
Chenard - wrong claim

### ISSUE THREAD

**Issue by yellow-panther** [cosinekitty/chenard#18]
[White "matmoi"]
[Black "xchenard64"]
[Result "1-0"]
[Number "4"]
[Termination "wrong claim"]
[BlackType "program"]
[WhiteType "program"]
[Variant "normal"]

1. e4 c5 2. Nf3 Nc6 3. Bb5 Nf6 4. Nc3 Nd4 5. e5 Nxb5 6. Nxb5 a6 7. Nc3 Ng4 8. h3 Nh6
9. d4 cxd4 10. Qxd4 Nf5 11. Qd3 e6 12. g4 Nh4 13. Nxh4 Qxh4 14. Bf4 Be7 15. Bg3 Qh6 16. f4 O-O
17. a4 Bb4 18. O-O-O Qg6 19. Qc4 Bxc3 20. bxc3 b5 21. axb5 Bb7 22. Rh2 axb5 23. Qxb5 Qe4 24. Kd2 Ra2 25. Qd3 Qxd3+ 26. Kxd3 Rc8 27. Bf2 Bf3 28. Re1 h5 29. g5 d6 30. exd6 Rc6 31. Bd4 Rxd6 32. Rb1 Rd8  33. h4 Rc8 34. Rf2 Bd5 35. Kd2 g6 36. Rh2 Be4 37. Kc1 Raa8 38. Rf2 Ra2 39. Be5 Raa8 40. Rd2 Bd5
 41. Rd3 Be4 42. Rd4 Bf5 43. Rdb4 Rd8 44. Rb8 Raxb8 45. Rxb8 Rxb8 46. Bxb8 Kf8 47. Be5 Ke8 48. c4 Kd7  49. c5 Kc6 50. Bd4 Kd5 51. c3 Bd3 52. Kd2 Ke4 53. c6 Ba6 54. Be5 Kf3 55. c7 Kg4 56. Ke1 Kxh4
 57. Kf2 Kg4 58. c4 h4 59. Kg2 Bc8 60. c5 Bb7+ 61. Kf2 h3 62. Kg1 Kg3 63. f5+ Kg4 64. fxe6 fxe6
 65. c6 Bc8 66. Kh2 Kh4 67. Bf4 e5 68. Bxe5 Kxg5 69. Bd6 Kf6 70. Bg3 g5 71. Be1 Ke5 72. Kg1 Kd5
 73. Kh1 g4 74. Bg3 Kxc6 75. Kg1 Kd5 76. Kf2 Kd4 77. Bd6 Ke4 78. Kg1 Ke3 79. Kh1 Kf3 80. Kh2 Bd7
 81. Be5 Ke4 82. Bc3 Kd5 83. Bd2 Ke6 84. Be1 Ke5 85. Bg3+ Ke4 86. Kg1 Kf3 87. Kh2 Be6 88. Be5 Bc8
 89. Bd6 Ke4 90. Kg1 Ke3 91. Kh1 Bf5 92. Kg1 Bd7 93. Bg3 Kf3 94. Kh2 Bf5 95. Bd6 Bc8 96. Bg3 Bf5
 97. Bd6 Bc8 98. Bg3 Bd7 99. Be5 Ke3 100. Kg1 Bc8 101. Bg3 Kd4 102. Bf2+ Ke4 103. Bg3 Ke3 104. Bd6 Bf5  105. Kh1 Kf2 106. Kh2 Kf3 107. Bg3 Ke4 108. Kg1 Kf3 109. Kh2 Ke4 110. Kg1 Ke3 111. Bd6 Be6 112. Bg3 Kd3  113. Kf1 Ke3 114. Kg1 Bc8 115. Bd6 Kd4 116. Kf2 Kd3 117. Kg1 Be6 118. Kf2 Bd7 119. Bg3 Bf5 120. Kg1 Ke2  121. Bd6 Bc8 122. Bg3 Bb7 123. Be5 Kd1 124. Kf1 1-0 

[_e1e_TmpResult.txt](https://github.com/cosinekitty/chenard/files/1778429/_e1e_TmpResult.txt)
[_e1e_TmpTable.txt](https://github.com/cosinekitty/chenard/files/1778430/_e1e_TmpTable.txt)
[Dbg00004.txt](https://github.com/cosinekitty/chenard/files/1778431/Dbg00004.txt)
[Dbg00004_matmoi_xchenard64.txt](https://github.com/cosinekitty/chenard/files/1778432/Dbg00004_matmoi_xchenard64.txt)
[EngOutp2_00004_xchenard64.txt](https://github.com/cosinekitty/chenard/files/1778435/EngOutp2_00004_xchenard64.txt)

**Comment by cosinekitty** [comment]
Thank you for the bug report. I will investigate.

**Comment by yellow-panther** [comment]
What problem caused the error message "wrong claim" by ChessGUI 0.245m
http://www.chess.hylogic.de/ and WB-2 protocol?

The difference bewteen v1 and v2 is described here:
http://home.hccnet.nl/h.g.muller/engine-intf.html -
http://hgm.nubati.net/CECP.html



2018-03-05 16:39 GMT+01:00 Don Cross <notifications@github.com>:

**Comment by cosinekitty** [comment]
The problem was claiming a draw by the 50 move rule when only 49 moves had occurred since the most recent capture or pawn move.
